<?php
	session_start();
	require('/pdf/fpdf.php');
	$pdf = new FPDF();
	$pdf->AliasNbPages();
	$pdf->AddPage();
	$pdf->SetY(10);
	$pdf->SetTextColor(0);
	$pdf->SetDrawColor(0,128,255);
	$pdf->SetLineWidth(.5);
	$pdf->SetFont('Arial','B',16);
	$pdf->Cell(50,10,'Campo',1);
	$pdf->Cell(50,10,'Respuesta',1);
	$pdf->Ln();
	$pdf->SetFont('Arial','',12);
	$pdf->Cell(50,10,"Edad:",1);
	$pdf->Cell(50,10,$_SESSION['edad'],1);
	$pdf->Ln();
	$pdf->Cell(50,10,"Nivel: ",1);
	$pdf->Cell(50,10,$_SESSION['nivel'],1);
	$pdf->Ln();
	$pdf->Cell(50,10,"Escuela: ",1);
	$pdf->Cell(50,10,$_SESSION['escuela'],1);
	$pdf->Ln();
	$pdf->Cell(50,10,utf8_decode("Compañia : "),1);
	$pdf->Cell(50,10,$_SESSION['compani'],1);
	$pdf->Ln();
	$pdf->Cell(50,10,"Localidad: ",1);
	$pdf->Cell(50,10,$_SESSION['localidad'],1);
	$pdf->Ln();
	$pdf->Cell(50,10,"Num. Llamadas: ",1);
	$pdf->Cell(50,10,$_SESSION['llamadas'],1);
	$pdf->Ln();
	$pdf->Output();
?>